#! /bin/bash

<<comment
Prerequisites:
-This was tested in an ubuntu 18.04 VM environment with 70GB of HHD space, and 8GB of allocated RAM

Description:
-This script adds t1s to the azure image, after an azure only build has been completed.


Usage:
". rebuild-add-t1s" runs from the build directory

 Written by:
 __  __     
/\ \/ /     
\ \  _"-.  
 \ \_\ \_\  
  \/_/\/_/ 
  
comment


lp='\e[1;35m'
NC='\e[0m'

#--------------START WORK--------------------
cd poky
export TEMPLATECONF=${TEMPLATECONF:-../meta-atmel/conf}
source oe-init-build-env build-microchip
cp -r -f -v ../../az.t1s.bblayers.conf conf/bblayers.conf
cp -r -f -v ../../az.t1s.local.conf conf/local.conf
MACHINE=sama5d27-wlsom1-ek-sd bitbake azure-t1s-demo

cd ../..
echo -e "${lp}Finished Adding 10Base-T1S!!! ${NC}\c"
echo -e "\c"

